import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import localFont from 'next/font/local'

const avenir = localFont({
  src: [
    {
      path: "/fonts/AvenirNext-Book.woff",
      weight: '300',
      style: 'normal',
    },
    {
      path: "/fonts/AvenirNext-Medium.woff",
      weight: '400',
      style: 'normal',
    },
    
    {
      path: "/fonts/AvenirNext-Bold.woff",
      weight: '500',
      style: 'light',
    },
    
  ],
  variable: '--font-avenir',
  display: 'swap', // important for performance
})
const sansumi = localFont({
  src: [
    {
       path: "/fonts/Sansumi-Bold-webfont.woff",
      weight: '300',
      style: 'normal',
    },
    {
       path: "/fonts/Sansumi-ExtraBold-webfont.woff",
      weight: '600',
      style: 'normal',
    },
   
    
  ],
  variable: '--font-sansumi',
  display: 'swap', // important for performance
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "ARTISTRY-RESIDENCE",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={` ${geistSans.variable} ${geistMono.variable} ${avenir.variable} ${sansumi.variable} antialiased`}
>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
