import type { Metadata, Viewport } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import localFont from 'next/font/local'

// Avenir font
const avenir = localFont({
  src: [
    { path: "/fonts/AvenirNext-Book.woff", weight: '300', style: 'normal' },
    { path: "/fonts/AvenirNext-Medium.woff", weight: '400', style: 'normal' },
    { path: "/fonts/AvenirNext-Bold.woff", weight: '500', style: 'normal' },
  ],
  variable: '--font-avenir',
  display: 'swap',
});

// Sansumi font
const sansumi = localFont({
  src: [
    { path: "/fonts/Sansumi-Bold-webfont.woff", weight: '500', style: 'normal' },
    { path: "/fonts/Sansumi-ExtraBold-webfont.woff", weight: '600', style: 'normal' },
  ],
  variable: '--font-sansumi',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "ARTISTRY-RESIDENCE",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${avenir.variable} ${sansumi.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}